package alt.sow.domain;

// Generated Oct 31, 2013 2:24:02 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Accesstype generated by hbm2java
 */
public class Accesstype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1052325756739118591L;
	private int idAccessType;
	private String accessTypeName;
	private Set<Access> accesses = new HashSet<Access>(0);

	public Accesstype() {
	}

	public Accesstype(int idAccessType) {
		this.idAccessType = idAccessType;
	}

	public Accesstype(int idAccessType, String accessTypeName,
			Set<Access> accesses) {
		this.idAccessType = idAccessType;
		this.accessTypeName = accessTypeName;
		this.accesses = accesses;
	}

	public Set<Access> getAccesses() {
		return this.accesses;
	}

	public String getAccessTypeName() {
		return this.accessTypeName;
	}

	public int getIdAccessType() {
		return this.idAccessType;
	}

	public void setAccesses(Set<Access> accesses) {
		this.accesses = accesses;
	}

	public void setAccessTypeName(String accessTypeName) {
		this.accessTypeName = accessTypeName;
	}

	public void setIdAccessType(int idAccessType) {
		this.idAccessType = idAccessType;
	}

}
