package alt.sow.domain;

// Generated Oct 31, 2013 2:24:02 PM by Hibernate Tools 3.6.0

/**
 * Access generated by hbm2java
 */
public class Access implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2924535653670469158L;
	private int idAccess;
	private Accesstype accesstype;
	private Role role;
	private String accessTableName;

	public Access() {
	}

	public Access(int idAccess) {
		this.idAccess = idAccess;
	}

	public Access(int idAccess, Accesstype accesstype, Role role,
			String accessTableName) {
		this.idAccess = idAccess;
		this.accesstype = accesstype;
		this.role = role;
		this.accessTableName = accessTableName;
	}

	public String getAccessTableName() {
		return this.accessTableName;
	}

	public Accesstype getAccesstype() {
		return this.accesstype;
	}

	public int getIdAccess() {
		return this.idAccess;
	}

	public Role getRole() {
		return this.role;
	}

	public void setAccessTableName(String accessTableName) {
		this.accessTableName = accessTableName;
	}

	public void setAccesstype(Accesstype accesstype) {
		this.accesstype = accesstype;
	}

	public void setIdAccess(int idAccess) {
		this.idAccess = idAccess;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((accessTableName == null) ? 0 : accessTableName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Access other = (Access) obj;
		if (accessTableName == null) {
			if (other.accessTableName != null)
				return false;
		} else if (!accessTableName.equals(other.accessTableName))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Access [accessTableName=" + accessTableName + "]";
	}

}
