package alt.sow.domain;

// Generated Oct 31, 2013 2:24:02 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -894807177357488260L;
	private int idAddress;
	private String hno;
	private String street1;
	private String street2;
	private String street3;
	private String town;
	private String city;
	private String country;
	private String pobox;
	private Set<Contact> contacts = new HashSet<Contact>(0);

	public Address() {
	}

	public Address(int idAddress) {
		this.idAddress = idAddress;
	}

	public Address(int idAddress, String hno, String street1, String street2,
			String street3, String town, String city, String country,
			String pobox, Set<Contact> contacts) {
		this.idAddress = idAddress;
		this.hno = hno;
		this.street1 = street1;
		this.street2 = street2;
		this.street3 = street3;
		this.town = town;
		this.city = city;
		this.country = country;
		this.pobox = pobox;
		this.contacts = contacts;
	}

	public String getCity() {
		return this.city;
	}

	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public String getCountry() {
		return this.country;
	}

	public String getHno() {
		return this.hno;
	}

	public int getIdAddress() {
		return this.idAddress;
	}

	public String getPobox() {
		return this.pobox;
	}

	public String getStreet1() {
		return this.street1;
	}

	public String getStreet2() {
		return this.street2;
	}

	public String getStreet3() {
		return this.street3;
	}

	public String getTown() {
		return this.town;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public void setHno(String hno) {
		this.hno = hno;
	}

	public void setIdAddress(int idAddress) {
		this.idAddress = idAddress;
	}

	public void setPobox(String pobox) {
		this.pobox = pobox;
	}

	public void setStreet1(String street1) {
		this.street1 = street1;
	}

	public void setStreet2(String street2) {
		this.street2 = street2;
	}

	public void setStreet3(String street3) {
		this.street3 = street3;
	}

	public void setTown(String town) {
		this.town = town;
	}

}
