package alt.sow.domain;

// Generated Oct 31, 2013 2:24:02 PM by Hibernate Tools 3.6.0

/**
 * Answer generated by hbm2java
 */
public class Answer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4601009954381488510L;
	private int idAnwer;
	private User user;
	private Question question;
	private String anwer;
	private Boolean correct;

	public Answer() {
	}

	public Answer(int idAnwer) {
		this.idAnwer = idAnwer;
	}

	public Answer(int idAnwer, User user, Question question, String anwer,
			Boolean correct) {
		this.idAnwer = idAnwer;
		this.user = user;
		this.question = question;
		this.anwer = anwer;
		this.correct = correct;
	}

	public String getAnwer() {
		return this.anwer;
	}

	public Boolean getCorrect() {
		return this.correct;
	}

	public int getIdAnwer() {
		return this.idAnwer;
	}

	public Question getQuestion() {
		return this.question;
	}

	public User getUser() {
		return this.user;
	}

	public void setAnwer(String anwer) {
		this.anwer = anwer;
	}

	public void setCorrect(Boolean correct) {
		this.correct = correct;
	}

	public void setIdAnwer(int idAnwer) {
		this.idAnwer = idAnwer;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
