package alt.sow.domain;

// Generated Oct 31, 2013 2:24:02 PM by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6932833336412528740L;
	private int idCourse;
	private User user;
	private String courseName;
	private String courseCode;
	private Set<Chapter> chapters = new HashSet<Chapter>(0);
	private Set<Exam> exams = new HashSet<Exam>(0);

	public Course() {
	}

	public Course(int idCourse) {
		this.idCourse = idCourse;
	}

	public Course(int idCourse, User user, String courseName,
			String courseCode, Set<Chapter> chapters, Set<Exam> exams) {
		this.idCourse = idCourse;
		this.user = user;
		this.courseName = courseName;
		this.courseCode = courseCode;
		this.chapters = chapters;
		this.exams = exams;
	}

	public Set<Chapter> getChapters() {
		return chapters;
	}

	public void setChapters(Set<Chapter> chapters) {
		this.chapters = chapters;
	}

	public String getCourseCode() {
		return this.courseCode;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public Set<Exam> getExams() {
		return this.exams;
	}

	public int getIdCourse() {
		return this.idCourse;
	}

	public User getUser() {
		return this.user;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public void setExams(Set<Exam> exams) {
		this.exams = exams;
	}

	public void setIdCourse(int idCourse) {
		this.idCourse = idCourse;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Override
	public String toString() {
		return "Course [idCourse=" + idCourse + ", user=" + user
				+ ", courseName=" + courseName + ", courseCode=" + courseCode
				+ "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idCourse;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Course other = (Course) obj;
		if (idCourse != other.idCourse)
			return false;
		return true;
	}

}
