package alt.sow.domain;

// Generated Oct 31, 2013 2:24:02 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Difficulty generated by hbm2java
 */
public class Difficulty implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 682436736690021346L;
	private int idDifficulty;
	private String difficultyName;
	private Set<Question> questions = new HashSet<Question>(0);

	public Difficulty() {
	}

	public Difficulty(int idDifficulty) {
		this.idDifficulty = idDifficulty;
	}

	public Difficulty(int idDifficulty, String difficultyName,
			Set<Question> questions) {
		this.idDifficulty = idDifficulty;
		this.difficultyName = difficultyName;
		this.questions = questions;
	}

	public String getDifficultyName() {
		return this.difficultyName;
	}

	public int getIdDifficulty() {
		return this.idDifficulty;
	}

	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setDifficultyName(String difficultyName) {
		this.difficultyName = difficultyName;
	}

	public void setIdDifficulty(int idDifficulty) {
		this.idDifficulty = idDifficulty;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
