package alt.sow.domain;

// Generated Nov 11, 2013 7:09:27 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Exam generated by hbm2java
 */
public class Exam implements java.io.Serializable {

	private int idExam;
	private Examtype examtype;
	private User user;
	private Profile profile;
	private Date conductedOn;
	private Integer marks;
	private Integer time;
	private Integer noquestion;
	private int cat;
	private String examCode;
	private Set<Course> courses = new HashSet<Course>(0);
	private Set<Student> students = new HashSet<Student>(0);
	private Set<Question> questions = new HashSet<Question>(0);

	public Exam() {
	}

	public Exam(int idExam) {
		this.idExam = idExam;
	}

	public Exam(int idExam, Examtype examtype, User user, Profile profile,
			Date conductedOn, Integer marks, Integer time, Integer noquestion,
			String examCode, Set<Course> courses, Set<Student> students,
			Set<Question> questions) {
		this.idExam = idExam;
		this.examtype = examtype;
		this.user = user;
		this.profile = profile;
		this.conductedOn = conductedOn;
		this.marks = marks;
		this.time = time;
		this.noquestion = noquestion;
		this.examCode = examCode;
		this.courses = courses;
		this.students = students;
		this.questions = questions;
	}

	public Exam(int idExam, Examtype examtype, User user, Profile profile,
			Date conductedOn, Integer marks, Integer time, Integer noquestion,
			int cat, String examCode, Set<Course> courses,
			Set<Student> students, Set<Question> questions) {
		super();
		this.idExam = idExam;
		this.examtype = examtype;
		this.user = user;
		this.profile = profile;
		this.conductedOn = conductedOn;
		this.marks = marks;
		this.time = time;
		this.noquestion = noquestion;
		this.cat = cat;
		this.examCode = examCode;
		this.courses = courses;
		this.students = students;
		this.questions = questions;
	}

	public int getCat() {
		return cat;
	}

	public void setCat(int cat) {
		this.cat = cat;
	}

	public int getIdExam() {
		return this.idExam;
	}

	public void setIdExam(int idExam) {
		this.idExam = idExam;
	}

	public Examtype getExamtype() {
		return this.examtype;
	}

	public void setExamtype(Examtype examtype) {
		this.examtype = examtype;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public Date getConductedOn() {
		return this.conductedOn;
	}

	public void setConductedOn(Date conductedOn) {
		this.conductedOn = conductedOn;
	}

	public Integer getMarks() {
		return this.marks;
	}

	public void setMarks(Integer marks) {
		this.marks = marks;
	}

	public Integer getTime() {
		return this.time;
	}

	public void setTime(Integer time) {
		this.time = time;
	}

	public Integer getNoquestion() {
		return this.noquestion;
	}

	public void setNoquestion(Integer noquestion) {
		this.noquestion = noquestion;
	}

	public String getExamCode() {
		return this.examCode;
	}

	public void setExamCode(String examCode) {
		this.examCode = examCode;
	}

	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
