package alt.sow.domain;

// Generated Oct 31, 2013 2:24:02 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Examtype generated by hbm2java
 */
public class Examtype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7398427256628115191L;
	private int idExamType;
	private String examTypeName;
	private Set<Exam> exams = new HashSet<Exam>(0);

	public Examtype() {
	}

	public Examtype(int idExamType) {
		this.idExamType = idExamType;
	}

	public Examtype(int idExamType, String examTypeName, Set<Exam> exams) {
		this.idExamType = idExamType;
		this.examTypeName = examTypeName;
		this.exams = exams;
	}

	public Set<Exam> getExams() {
		return this.exams;
	}

	public String getExamTypeName() {
		return this.examTypeName;
	}

	public int getIdExamType() {
		return this.idExamType;
	}

	public void setExams(Set<Exam> exams) {
		this.exams = exams;
	}

	public void setExamTypeName(String examTypeName) {
		this.examTypeName = examTypeName;
	}

	public void setIdExamType(int idExamType) {
		this.idExamType = idExamType;
	}

}
