package alt.sow.domain;

// Generated Oct 31, 2013 2:24:02 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import com.sn.util.StringUtils;

/**
 * Name generated by hbm2java
 */
public class Name implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3454500227744232111L;
	private int idName;
	private String firstName;
	private String middleName;
	private String lastName;
	private String surName;
	private Set<Profile> profilesForNameIdFather = new HashSet<Profile>(0);
	private Set<Profile> profilesForNameIdName = new HashSet<Profile>(0);

	public Name() {
	}

	public Name(int idName) {
		this.idName = idName;
	}

	public Name(int idName, String firstName, String middleName,
			String lastName, String surName,
			Set<Profile> profilesForNameIdFather,
			Set<Profile> profilesForNameIdName) {
		this.idName = idName;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.surName = surName;
		this.profilesForNameIdFather = profilesForNameIdFather;
		this.profilesForNameIdName = profilesForNameIdName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public int getIdName() {
		return this.idName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public Set<Profile> getProfilesForNameIdFather() {
		return this.profilesForNameIdFather;
	}

	public Set<Profile> getProfilesForNameIdName() {
		return this.profilesForNameIdName;
	}

	public String getSurName() {
		return this.surName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public void setIdName(int idName) {
		this.idName = idName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public void setProfilesForNameIdFather(Set<Profile> profilesForNameIdFather) {
		this.profilesForNameIdFather = profilesForNameIdFather;
	}

	public void setProfilesForNameIdName(Set<Profile> profilesForNameIdName) {
		this.profilesForNameIdName = profilesForNameIdName;
	}

	public void setSurName(String surName) {
		this.surName = surName;
	}

	@Override
	public String toString() {
		String string = "";
		if (!StringUtils.isBlank(firstName)) {
			string = firstName;
		}
		if (!StringUtils.isBlank(lastName)) {
			string = string + " " + lastName;
		}
		if (StringUtils.isBlank(string.trim())) {
			string = "name not set";
		}
		System.out.println("Name:" + string);
		return string;
	}
}
