package alt.sow.domain;

// Generated Oct 31, 2013 2:24:02 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1076108037499771816L;
	private int idStudent;
	private Profile profile;
	private User user;
	private Exam exam;
	private String studentCode;
	private Set<Result> results = new HashSet<Result>(0);

	public Student() {
	}

	public Student(int idStudent) {
		this.idStudent = idStudent;
	}

	public Student(int idStudent, Profile profile, User user, Exam exam,
			String studentCode, Set<Result> results) {
		this.idStudent = idStudent;
		this.profile = profile;
		this.user = user;
		this.exam = exam;
		this.studentCode = studentCode;
		this.results = results;
	}

	public Exam getExam() {
		return this.exam;
	}

	public int getIdStudent() {
		return this.idStudent;
	}

	public Profile getProfile() {
		return this.profile;
	}

	public Set<Result> getResults() {
		return this.results;
	}

	public String getStudentCode() {
		return this.studentCode;
	}

	public User getUser() {
		return this.user;
	}

	public void setExam(Exam exam) {
		this.exam = exam;
	}

	public void setIdStudent(int idStudent) {
		this.idStudent = idStudent;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public void setResults(Set<Result> results) {
		this.results = results;
	}

	public void setStudentCode(String studentCode) {
		this.studentCode = studentCode;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
