package alt.sow.domain;

// Generated Oct 31, 2013 2:24:02 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -213635313533179597L;
	private int idUser;
	private Profile profile;
	private Role role;
	private String username;
	private String password;
	private Date lastLogin;
	private Boolean firstLogin;
	private Boolean authenticated;
	private Boolean blocked;
	private String userCode;
	private Set<Certificate> certificatesForAddedBy = new HashSet<Certificate>(
			0);
	private Set<Result> results = new HashSet<Result>(0);
	private Set<Course> courses = new HashSet<Course>(0);
	private Set<Student> students = new HashSet<Student>(0);
	private Set<Exam> exams = new HashSet<Exam>(0);
	private Set<Certificate> certificatesForUserIdTeacher = new HashSet<Certificate>(
			0);
	private Set<Question> questions = new HashSet<Question>(0);
	private Set<Answer> answers = new HashSet<Answer>(0);
	private Set<Chapter> chapters = new HashSet<Chapter>(0);

	public User() {
	}

	public User(int idUser) {
		this.idUser = idUser;
	}

	public User(int idUser, Profile profile, Role role, String username,
			String password, Date lastLogin, Boolean firstLogin,
			Boolean authenticated, Boolean blocked, String userCode,
			Set<Certificate> certificatesForAddedBy, Set<Result> results,
			Set<Course> courses, Set<Student> students, Set<Exam> exams,
			Set<Certificate> certificatesForUserIdTeacher,
			Set<Question> questions, Set<Answer> answers, Set<Chapter> chapters) {
		this.idUser = idUser;
		this.profile = profile;
		this.role = role;
		this.username = username;
		this.password = password;
		this.lastLogin = lastLogin;
		this.firstLogin = firstLogin;
		this.authenticated = authenticated;
		this.blocked = blocked;
		this.userCode = userCode;
		this.certificatesForAddedBy = certificatesForAddedBy;
		this.results = results;
		this.courses = courses;
		this.students = students;
		this.exams = exams;
		this.certificatesForUserIdTeacher = certificatesForUserIdTeacher;
		this.questions = questions;
		this.answers = answers;
		this.chapters = chapters;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		User other = (User) obj;
		if (idUser != other.idUser)
			return false;
		return true;
	}

	public Set<Answer> getAnswers() {
		return this.answers;
	}

	public Boolean getAuthenticated() {
		return this.authenticated;
	}

	public Boolean getBlocked() {
		return this.blocked;
	}

	public Set<Certificate> getCertificatesForAddedBy() {
		return this.certificatesForAddedBy;
	}

	public Set<Certificate> getCertificatesForUserIdTeacher() {
		return this.certificatesForUserIdTeacher;
	}

	public Set<Chapter> getChapters() {
		return this.chapters;
	}

	public Set<Course> getCourses() {
		return this.courses;
	}

	public Set<Exam> getExams() {
		return this.exams;
	}

	public Boolean getFirstLogin() {
		return this.firstLogin;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public Date getLastLogin() {
		return this.lastLogin;
	}

	public String getPassword() {
		return this.password;
	}

	public Profile getProfile() {
		return this.profile;
	}

	public Set<Question> getQuestions() {
		return this.questions;
	}

	public Set<Result> getResults() {
		return this.results;
	}

	public Role getRole() {
		return this.role;
	}

	public Set<Student> getStudents() {
		return this.students;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public String getUsername() {
		return this.username;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idUser;
		return result;
	}

	public void setAnswers(Set<Answer> answers) {
		this.answers = answers;
	}

	public void setAuthenticated(Boolean authenticated) {
		this.authenticated = authenticated;
	}

	public void setBlocked(Boolean blocked) {
		this.blocked = blocked;
	}

	public void setCertificatesForAddedBy(
			Set<Certificate> certificatesForAddedBy) {
		this.certificatesForAddedBy = certificatesForAddedBy;
	}

	public void setCertificatesForUserIdTeacher(
			Set<Certificate> certificatesForUserIdTeacher) {
		this.certificatesForUserIdTeacher = certificatesForUserIdTeacher;
	}

	public void setChapters(Set<Chapter> chapters) {
		this.chapters = chapters;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

	public void setExams(Set<Exam> exams) {
		this.exams = exams;
	}

	public void setFirstLogin(Boolean firstLogin) {
		this.firstLogin = firstLogin;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

	public void setResults(Set<Result> results) {
		this.results = results;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
